name: eyro_toast
description: A simple yet powerful Flutter plugin for showing Toast Mobile, Desktop and Web.
version: 1.0.0
homepage: https://github.com/rizalgunawan/eyro_toast

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.eyrotoast.eyro_toast
        pluginClass: EyroToastPlugin
      ios:
        pluginClass: EyroToastPlugin